### PR TITLE
fix:repeating passwords

### LINKED ISSUE #6: Repetitve words in word list
### Repeat of words
 1. Same words more than once causing **file size to increase**.
 2. Removing these words will result in more than 10% efficiency
 3. Implement **data structure** to prevent this issue.
 4. Use **Set** or any other structure with at most **O(n)** complexity.

Remember to use conventional commits and branch name should be issue related.

### PR DESCRIPTION
**Pull request by AkMo3**
closes #6

### CODE REVIEW

File: Main.java [hunk 1]
```diff
@@ -37,47 +39,61 @@ public static void main(String[] args) {
 					for (int j = i; j <= Birthdate.length(); j++) {
 						if (j >= i) {
 							String password = Parameter_Value.get(0) + Birthdate.substring(i, j);
-							fw.write(password);
-							fw.write("\n");
+							if (IsUnique(Old_Passwords, password)) {
+								fw.write(password);
```
Comment (AkMo3) [inline Main.java:43]: Try to include file writing functions inside IsUnique() function.

File: Main.java [hunk 2]
```diff
@@ -37,47 +39,61 @@ public static void main(String[] args) {
...
+								fw.write("\n");
+							}
 							for (int len = 0; len < Parameter_Value.size(); len++) {
 								String name = Parameter_Value.get(len);
 								for (int s = 0; s < Special_Char.length; s++) {
 									password = name + Special_Char[s] + Birthdate.substring(i, j);
-									fw.write(password);
-									fw.write("\n");
+									if (IsUnique(Old_Passwords, password)) {
+										fw.write(password);
```
Comment (AkMo3) [inline Main.java:51]: Same as above

File: Main.java [hunk 3]
```diff
@@ -131,4 +146,12 @@ private static void FormatBirthdate(ArrayList<String> Birthdate) {
 		}
 	}
 
+	private static boolean IsUnique(HashSet<String> Old_Passwords, String New_Passwords) {
```
Comment (AkMo3) [inline Main.java:149]: HashSet also causes collisions, Need to be careful about that.

**Review by AkMo3 — COMMENTED** [review]
File writer is called quite a few times, include it side function to prevent the repetition.

File: Main.java [hunk 4]
```diff
@@ -37,47 +39,61 @@ public static void main(String[] args) {
...
+											fw.write(password);
+											fw.write("\n");
+										}
 									}
 								}
 
 								for (int s1 = 0; s1 < Special_Char.length; s1++) {
 									for (int s2 = 0; s2 < Special_Char.length; s2++)
 										password = name + Special_Char[s1] + Birthdate.substring(i, j)
 												+ Special_Char[s1];
```
Comment (AkMo3) [inline Main.java:75]: Special chars are coming same in output due to this small typo.

password = name + Special_Char[s1] + Birthdate.substring(i,j) + Special_Char[s2];
