### PR TITLE
fix:birthdate formatting

### LINKED ISSUE #3: Add function to format birthdate
### Birthdate Format

     1. Right now if the date of birth is 09121991 i.e. 9th December 1991, the program fuses the date as ( 09 ) whereas it is highly likely that the password may use 9 in place of 09.
     2. Similarly in 19071991, in password may contain ( 7 ) not ( 07 ).
     3. Also the format of password may in DDMMYY .

The above issue are to be solve in this PR.

### Points to remember

    1. Use conventional commits
    2. Name of branch should be of the Title of PR

### PR DESCRIPTION
**Pull request by AkMo3**
closes #3

### CODE REVIEW

File: Main.java [hunk 1]
```diff
@@ -4,86 +4,130 @@
...
-				fw.close();
-		}catch(Exception e) {System.out.println(e);}
-		
+			}
+
+			fw.close();
+
+			sc.close();
+		} catch (Exception e) {
+			System.out.println(e);
```
Comment (AkMo3) [inline Main.java:93]: add stack trace for now

**Review by AkMo3 — COMMENTED** [review]
Add stack trace in while catching the error for easy debuggingg.
